### PR TITLE
Fix issue where stroke and fill could be rendered in incorrect order

### LINKED ISSUE #1902: Animation issue with new rendering engine
## Which Version of Lottie are you using?

Lottie 4.0.1

I observed an issue with one of our animation when I use the CoreAnimation rendering engine (the sun rays do not appear). So I would like to know if it's an issue from the rendering engine or if we should modify something in our animation.

## Expected Behavior 

The sun is not bald.

Screenshot 2023-01-06 at 17 28 33

## Actual Behavior

Screenshot 2023-01-06 at 17 28 49

## Animation JSON
https://app.lottiefiles.com/share/ac8cca74-4a94-47ee-9893-3d61761a7eb5
```json
{"v":"5.5.10","fr":15,"ip":0,"op":60,"w":320,"h":320,"nm":"06.05 - Sun Bodymovin","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Eyes","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"t":0,"s":[0],"h":1},{"t":1,"s":[0.017],"h":1},{"t":2,"s":[0.069],"h":1},{"t":3,"s":[0.163],"h":1},{"t":4,"s":[0.303],"h":1},{"t":5,"s":[0.497],"h":1},{"t":6,"s":[0.755],"h":1},{"t":7,"s":[1.088],"h":1},{"t":8,"s":[1.511],"h":1},{"t":9,"s":[2.043],"h":1},{"t":10,"s":[2.71],"h":1},{"t":11,"s":[3.543],"h":1},{"t":12,"s":[4.583],"h":1},{"t":13,"s":[5.863],"h":1},{"t":14,"s":[7.39],"h":1},{"t":15,"s":[9.088],"h":1},{"t":16,"s":[10.786],"h":1},{"t":17,"s":[12.313],"h":1},{"t":18,"s":[13.594],"h":1},{"t":19,"s":[14.633],"h":1},{"t":20,"s":[15.467],"h":1},{"t":21,"s":[16.133],"h":1},{"t":22,"s":[16.666],"h":1},{"t":23,"s":[17.088],"h":1},{"t":24,"s":[17.421],"h":1},{"t":25,"s":[17.679],"h":1},{"t":26,"s":[17.873],"h":1},{"t":27,"s":[18.014],"h":1},{"t":28,"s":[18.107],"h":1},{"t":29,"s":[18.16],"h":1},{"t":30,"s":[18.176],"h":1},{"t":31,"s":[18.16],"h":1},{"t":32,"s":[18.107],"h":1},{"t":33,"s":[18.014],"h":1},{"t":34,"s":[17.873],"h":1},{"t":35,"s":[17.679],"h":1},{"t":36,"s":[17.421],"h":1},{"t":37,"s":[17.088],"h":1},{"t":38,"s":[16.666],"h":1},{"t":39,"s":[16.133],"h":1},{"t":40,"s":[15.467],"h":1},{"t":41,"s":[14.633],"h":1},{"t":42,"s":[13.594],"h":1},{"t":43,"s":[12.313],"h":1},{"t":44,"s":[10.786],"h":1},{"t":45,"s":[9.088],"h":1},{"t":46,"s":[7.39],"h":1},{"t":47,"s":[5.863],"h":1},{"t":48,"s":[4.583],"h":1},{"t":49,"s":[3.543],"h":1},{"t":50,"s":[2.71],"h":1},{"t":51,"s":[2.043],"h":1},{"t":52,"s":[1.511],"h":1},{"t":53,"s":[1.088],"h":1},{"t":54,"s":[0.755],"h":1},{"t":55,"s":[0.497],"h":1},{"t":56,"s":[0.303],"h":1},{"t":57,"s":[0.163],"h":1},{"t":58,"s":[0.069],"h":1},{"t":59,"s":[0.017],"h":1},{"t":60,"s":[0],"h":1}],"ix":10},"p":{"a":1,"k":[{"t":0,"s":[162,131,0],"h":1},{"t":1,"s":[161.989,131.012,0],"h":1},{"t":2,"s":[161.954,131.051,0],"h":1},{"t":3,"s":[161.891,131.12,0],"h":1},{"t":4,"s":[161.796,131.223,0],"h":1},{"t":5,"s":[161.662,131.364,0],"h":1},{"t":6,"s":[161.482,131.548,0],"h":1},{"t":7,"s":[161.245,131.78,0],"h":1},{"t":8,"s":[160.935,132.066,0],"h":1},{"t":9,"s":[160.532,132.412,0],"h":1},{"t":10,"s":[160.008,132.821,0],"h":1},{"t":11,"s":[159.324,133.294,0],"h":1},{"t":12,"s":[158.434,133.824,0],"h":1},{"t":13,"s":[157.288,134.392,0],"h":1},{"t":14,"s":[155.872,134.956,0],"h":1},{"t":15,"s":[154.251,135.461,0],"h":1},{"t":16,"s":[152.602,135.859,0],"h":1},{"t":17,"s":[151.1,136.141,0],"h":1},{"t":18,"s":[149.832,136.333,0],"h":1},{"t":19,"s":[148.798,136.461,0],"h":1},{"t":20,"s":[147.966,136.548,0],"h":1},{"t":21,"s":[147.299,136.609,0],"h":1},{"t":22,"s":[146.766,136.652,0],"h":1},{"t":23,"s":[146.342,136.683,0],"h":1},{"t":24,"s":[146.009,136.705,0],"h":1},{"t":25,"s":[145.75,136.721,0],"h":1},{"t":26,"s":[145.554,136.733,0],"h":1},{"t":27,"s":[145.413,136.741,0],"h":1},{"t":28,"s":[145.32,136.746,0],"h":1},{"t":29,"s":[145.267,136.749,0],"h":1},{"t":30,"s":[145.25,136.75,0],"h":1},{"t":31,"s":[145.265,136.762,0],"h":1},{"t":32,"s":[145.312,136.8,0],"h":1},{"t":33,"s":[145.397,136.867,0],"h":1},{"t":34,"s":[145.526,136.967,0],"h":1},{"t":35,"s":[145.706,137.102,0],"h":1},{"t":36,"s":[145.949,137.276,0],"h":1},{"t":37,"s":[146.269,137.491,0],"h":1},{"t":38,"s":[146.685,137.749,0],"h":1},{"t":39,"s":[147.224,138.045,0],"h":1},{"t":40,"s":[147.923,138.368,0],"h":1},{"t":41,"s":[148.828,138.691,0],"h":1},{"t":42,"s":[149.994,138.954,0],"h":1},{"t":43,"s":[151.46,139.056,0],"h":1},{"t":44,"s":[153.201,138.861,0],"h":1},{"t":45,"s":[155.062,138.286,0],"h":1},{"t":46,"s":[156.793,137.405,0],"h":1},{"t":47,"s":[158.227,136.402,0],"h":1},{"t":48,"s":[159.329,135.43,0],"h":1},{"t":49,"s":[160.148,134.561,0],"h":1},{"t":50,"s":[160.745,133.816,0],"h":1},{"t":51,"s":[161.179,133.185,0],"h":1},{"t":52,"s":[161.488,132.655,0],"h":1},{"t":53,"s":[161.703,132.216,0],"h":1},{"t":54,"s":[161.844,131.857,0],"h":1},{"t":55,"s":[161.93,131.57,0],"h":1},{"t":56,"s":[161.976,131.35,0],"h":1},{"t":57,"s":[161.996,131.188,0],"h":1},{"t":58,"s":[162.001,131.08,0],"h":1},{"t":59,"s":[162.001,131.019,0],"h":1},{"t":60,"s":[162,131,0],"h":1}],"ix":2},"a":{"a":0,"k":[0.839,-12.161,0],"ix":1},"s":{"a":0,"k":[238.466,238.466,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"t":0,"s":[{"i":[[-0.059,-2.721],[1.331,-0.026],[0.059,2.721],[-1.331,0.026]],"o":[[0.053,2.728],[-1.324,0.026],[-0.053,-2.728],[1.331,-0.026]],"v":[[-1.763,-11.891],[-4.069,-6.909],[-6.573,-11.792],[-4.267,-16.773]],"c":true}],"h":1},{"t":2,"s":[{"i":[[-0.078,-0.949],[1.331,-0.026],[0.021,0.627],[-1.331,0.026]],"o":[[0.085,0.935],[-1.324,0.026],[0.073,-0.841],[1.331,-0.026]],"v":[[-1.186,-11.995],[-4.331,-11.155],[-7.464,-11.739],[-4.319,-12.947]],"c":true}],"h":1},{"t":4,"s":[{"i":[[-0.059,-2.721],[1.331,-0.026],[0.059,2.721],[-1.331,0.026]],"o":[[0.053,2.728],[-1.324,0.026],[-0.053,-2.728],[1.331,-0.026]],"v":[[-1.763,-11.891],[-4.069,-6.909],[-6.573,-11.792],[-4.267,-16.773]],"c":true}],"h":1}],"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0,0,0,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":2,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"t":0,"s":[{"i":[[-0.441,-2.688],[1.305,-0.211],[0.441,2.688],[-1.305,0.211]],"o":[[0.441,2.688],[-1.311,0.211],[-0.441,-2.688],[1.311,-0.217]],"v":[[7.851,-13.465],[6.276,-8.207],[3.107,-12.688],[4.682,-17.946]],"c":true}],"h":1},{"t":2,"s":[{"i":[[-0.146,-0.95],[1.305,-0.211],[0.038,0.789],[-1.305,0.211]],"o":[[0.116,0.623],[-1.311,0.211],[-0.014,-0.836],[1.311,-0.217]],"v":[[8.585,-13.57],[5.962,-12.453],[2.949,-12.74],[5.678,-14.067]],"c":true}],"h":1},{"t":4,"s":[{"i":[[-0.441,-2.688],[1.305,-0.211],[0.441,2.688],[-1.305,0.211]],"o":[[0.441,2.688],[-1.311,0.211],[-0.441,-2.688],[1.311,-0.217]],"v":[[7.851,-13.465],[6.276,-8.207],[3.107,-12.688],[4.682,-17.946]],"c":true}],"h":1}],"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0,0,0,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 2","np":2,"cix":2,"bm":0,"ix":2,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":60,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"Mouth","parent":1,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[0,0,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[-0.277,-0.092],[-3.776,0.824],[-1.726,0.876],[-1.542,1.252],[0,0],[-0.211,-0.257],[0.171,-0.217],[1.825,-1.1],[2.102,-0.402],[2.102,0.29],[1.878,0.929],[-0.145,0.297]],"o":[[3.762,1.252],[1.891,-0.389],[1.72,-0.896],[0,0],[0.257,-0.211],[0.178,0.217],[-1.292,1.674],[-1.832,1.094],[-2.102,0.415],[-2.109,-0.29],[-0.297,-0.145],[0.125,-0.264]],"v":[[-8.978,-1.987],[2.56,-1.222],[7.983,-3.199],[12.866,-6.454],[12.873,-6.461],[13.716,-6.375],[13.723,-5.631],[8.952,-1.473],[2.975,0.781],[-3.396,0.965],[-9.426,-0.886],[-9.696,-1.69]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0,0,0,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":2,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":60,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":4,"nm":"Circle","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[160,160,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[238.466,238.466,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,-17.805],[17.238,0],[0,17.811],[-17.238,0]],"o":[[0,17.804],[-17.238,0],[0,-17.805],[17.238,0]],"v":[[31.744,1.117],[0.531,33.359],[-30.683,1.117],[0.531,-31.125]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0,0,0,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":3.156,"ix":5},"lc":2,"lj":2,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[1,1,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":60,"st":0,"bm":0},{"ddd":0,"ind":4,"ty":4,"nm":"Rays","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.833],"y":[1]},"o":{"x":[0.65],"y":[0]},"t":-15,"s":[0]},{"t":0,"s":[45],"h":1},{"t":1,"s":[51.965],"h":1},{"t":2,"s":[58.311],"h":1},{"t":3,"s":[63.76],"h":1},{"t":4,"s":[68.334],"h":1},{"t":5,"s":[72.161],"h":1},{"t":6,"s":[75.383],"h":1},{"t":7,"s":[78.115],"h":1},{"t":8,"s":[80.45],"h":1},{"t":9,"s":[82.459],"h":1},{"t":10,"s":[84.195],"h":1},{"t":11,"s":[85.701],"h":1},{"t":12,"s":[87.01],"h":1},{"t":13,"s":[88.149],"h":1},{"t":14,"s":[89.14],"h":1},{"t":15,"s":[90],"h":1},{"t":16,"s":[90.86],"h":1},{"t":17,"s":[91.851],"h":1},{"t":18,"s":[92.99],"h":1},{"t":19,"s":[94.299],"h":1},{"t":20,"s":[95.805],"h":1},{"t":21,"s":[97.541],"h":1},{"t":22,"s":[99.55],"h":1},{"t":23,"s":[101.885],"h":1},{"t":24,"s":[104.617],"h":1},{"t":25,"s":[107.839],"h":1},{"t":26,"s":[111.666],"h":1},{"t":27,"s":[116.24],"h":1},{"t":28,"s":[121.689],"h":1},{"t":29,"s":[128.035],"h":1},{"t":30,"s":[135],"h":1},{"t":31,"s":[141.965],"h":1},{"t":32,"s":[148.311],"h":1},{"t":33,"s":[153.76],"h":1},{"t":34,"s":[158.334],"h":1},{"t":35,"s":[162.161],"h":1},{"t":36,"s":[165.383],"h":1},{"t":37,"s":[168.115],"h":1},{"t":38,"s":[170.45],"h":1},{"t":39,"s":[172.459],"h":1},{"t":40,"s":[174.195],"h":1},{"t":41,"s":[175.701],"h":1},{"t":42,"s":[177.01],"h":1},{"t":43,"s":[178.149],"h":1},{"t":44,"s":[179.14],"h":1},{"t":45,"s":[180],"h":1},{"t":46,"s":[180.86],"h":1},{"t":47,"s":[181.851],"h":1},{"t":48,"s":[182.99],"h":1},{"t":49,"s":[184.299],"h":1},{"t":50,"s":[185.805],"h":1},{"t":51,"s":[187.541],"h":1},{"t":52,"s":[189.55],"h":1},{"t":53,"s":[191.885],"h":1},{"t":54,"s":[194.617],"h":1},{"t":55,"s":[197.839],"h":1},{"t":56,"s":[201.666],"h":1},{"t":57,"s":[206.24],"h":1},{"t":58,"s":[211.689],"h":1},{"t":59,"s":[218.035],"h":1},{"t":60,"s":[225],"h":1},{"i":{"x":[0.35],"y":[0.827]},"o":{"x":[0.65],"y":[0.173]},"t":75,"s":[270]},{"i":{"x":[0.35],"y":[-30.72]},"o":{"x":[0.167],"y":[0]},"t":105,"s":[360]},{"t":166,"s":[360]}],"ix":10},"p":{"a":0,"k":[160,160,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[200,200,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ty":"sr","sy":1,"d":1,"pt":{"a":0,"k":12,"ix":3},"p":{"a":0,"k":[0,0],"ix":4},"r":{"a":0,"k":0,"ix":5},"ir":{"a":1,"k":[{"i":{"x":[0.833],"y":[1]},"o":{"x":[0.65],"y":[0]},"t":-15,"s":[44]},{"t":0,"s":[40],"h":1},{"t":1,"s":[40.053],"h":1},{"t":2,"s":[40.228],"h":1},{"t":3,"s":[40.549],"h":1},{"t":4,"s":[41.008],"h":1},{"t":5,"s":[41.553],"h":1},{"t":6,"s":[42.099],"h":1},{"t":7,"s":[42.583],"h":1},{"t":8,"s":[42.983],"h":1},{"t":9,"s":[43.3],"h":1},{"t":10,"s":[43.543],"h":1},{"t":11,"s":[43.724],"h":1},{"t":12,"s":[43.853],"h":1},{"t":13,"s":[43.938],"h":1},{"t":14,"s":[43.985],"h":1},{"t":15,"s":[44],"h":1},{"t":16,"s":[43.985],"h":1},{"t":17,"s":[43.933],"h":1},{"t":18,"s":[43.834],"h":1},{"t":19,"s":[43.668],"h":1},{"t":20,"s":[43.404],"h":1},{"t":21,"s":[42.992],"h":1},{"t":22,"s":[42.374],"h":1},{"t":23,"s":[41.626],"h":1},{"t":24,"s":[41.008],"h":1},{"t":25,"s":[40.596],"h":1},{"t":26,"s":[40.332],"h":1},{"t":27,"s":[40.166],"h":1},{"t":28,"s":[40.067],"h":1},{"t":29,"s":[40.015],"h":1},{"t":30,"s":[40],"h":1},{"t":31,"s":[40.053],"h":1},{"t":32,"s":[40.228],"h":1},{"t":33,"s":[40.549],"h":1},{"t":34,"s":[41.008],"h":1},{"t":35,"s":[41.553],"h":1},{"t":36,"s":[42.099],"h":1},{"t":37,"s":[42.583],"h":1},{"t":38,"s":[42.983],"h":1},{"t":39,"s":[43.3],"h":1},{"t":40,"s":[43.543],"h":1},{"t":41,"s":[43.724],"h":1},{"t":42,"s":[43.853],"h":1},{"t":43,"s":[43.938],"h":1},{"t":44,"s":[43.985],"h":1},{"t":45,"s":[44],"h":1},{"t":46,"s":[43.985],"h":1},{"t":47,"s":[43.933],"h":1},{"t":48,"s":[43.834],"h":1},{"t":49,"s":[43.668],"h":1},{"t":50,"s":[43.404],"h":1},{"t":51,"s":[42.992],"h":1},{"t":52,"s":[42.374],"h":1},{"t":53,"s":[41.626],"h":1},{"t":54,"s":[41.008],"h":1},{"t":55,"s":[40.596],"h":1},{"t":56,"s":[40.332],"h":1},{"t":57,"s":[40.166],"h":1},{"t":58,"s":[40.067],"h":1},{"t":59,"s":[40.015],"h":1},{"t":60,"s":[40],"h":1},{"i":{"x":[0.35],"y":[1]},"o":{"x":[0.65],"y":[0]},"t":75,"s":[44]},{"i":{"x":[0.35],"y":[1]},"o":{"x":[0.35],"y":[0]},"t":90,"s":[40]},{"t":105,"s":[44]}],"ix":6},"is":{"a":0,"k":0,"ix":8},"or":{"a":1,"k":[{"i":{"x":[0.833],"y":[1]},"o":{"x":[0.65],"y":[0]},"t":-15,"s":[53]},{"t":0,"s":[56],"h":1},{"t":1,"s":[55.961],"h":1},{"t":2,"s":[55.829],"h":1},{"t":3,"s":[55.589],"h":1},{"t":4,"s":[55.244],"h":1},{"t":5,"s":[54.835],"h":1},{"t":6,"s":[54.426],"h":1},{"t":7,"s":[54.063],"h":1},{"t":8,"s":[53.763],"h":1},{"t":9,"s":[53.525],"h":1},{"t":10,"s":[53.343],"h":1},{"t":11,"s":[53.207],"h":1},{"t":12,"s":[53.11],"h":1},{"t":13,"s":[53.046],"h":1},{"t":14,"s":[53.011],"h":1},{"t":15,"s":[53],"h":1},{"t":16,"s":[53.011],"h":1},{"t":17,"s":[53.05],"h":1},{"t":18,"s":[53.125],"h":1},{"t":19,"s":[53.249],"h":1},{"t":20,"s":[53.447],"h":1},{"t":21,"s":[53.756],"h":1},{"t":22,"s":[54.22],"h":1},{"t":23,"s":[54.78],"h":1},{"t":24,"s":[55.244],"h":1},{"t":25,"s":[55.553],"h":1},{"t":26,"s":[55.751],"h":1},{"t":27,"s":[55.875],"h":1},{"t":28,"s":[55.95],"h":1},{"t":29,"s":[55.989],"h":1},{"t":30,"s":[56],"h":1},{"t":31,"s":[55.961],"h":1},{"t":32,"s":[55.829],"h":1},{"t":33,"s":[55.589],"h":1},{"t":34,"s":[55.244],"h":1},{"t":35,"s":[54.835],"h":1},{"t":36,"s":[54.426],"h":1},{"t":37,"s":[54.063],"h":1},{"t":38,"s":[53.763],"h":1},{"t":39,"s":[53.525],"h":1},{"t":40,"s":[53.343],"h":1},{"t":41,"s":[53.207],"h":1},{"t":42,"s":[53.11],"h":1},{"t":43,"s":[53.046],"h":1},{"t":44,"s":[53.011],"h":1},{"t":45,"s":[53],"h":1},{"t":46,"s":[53.011],"h":1},{"t":47,"s":[53.05],"h":1},{"t":48,"s":[53.125],"h":1},{"t":49,"s":[53.249],"h":1},{"t":50,"s":[53.447],"h":1},{"t":51,"s":[53.756],"h":1},{"t":52,"s":[54.22],"h":1},{"t":53,"s":[54.78],"h":1},{"t":54,"s":[55.244],"h":1},{"t":55,"s":[55.553],"h":1},{"t":56,"s":[55.751],"h":1},{"t":57,"s":[55.875],"h":1},{"t":58,"s":[55.95],"h":1},{"t":59,"s":[55.989],"h":1},{"t":60,"s":[56],"h":1},{"i":{"x":[0.35],"y":[1]},"o":{"x":[0.65],"y":[0]},"t":75,"s":[53]},{"i":{"x":[0.35],"y":[1]},"o":{"x":[0.35],"y":[0]},"t":90,"s":[56]},{"t":105,"s":[53]}],"ix":7},"os":{"a":0,"k":0,"ix":9},"ix":1,"nm":"Polystar Path 1","mn":"ADBE Vector Shape - Star","hd":false},{"ty":"fl","c":{"a":0,"k":[0,0,0,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"st","c":{"a":0,"k":[1,1,1,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":16,"ix":5},"lc":2,"lj":2,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":60,"st":0,"bm":0}],"markers":[]}
```

### PR DESCRIPTION
**Pull request by calda**
This PR fixes an issue where `Stroke` and `Fill` items could be rendered in an incorrect order. Fixes #1902. 

It turns out the order of `Stroke` and `Fill`s in a shape layer actually matters. I hadn't noticed this before because almost all of our animations render the stroke on top of the fill, which happens to be the same way that `CAShapeLayer` works. Lottie also supports rendering a fill on top of a stroke, which was previously not handled properly by the Core Animation rendering engine.

| Before (stroke rendered above fill) | After (fill rendered above stroke) |
| ---- | ---- |
| Simulator Screen Shot - iPhone 8 - 2023-01-06 at 11 45 27 | Simulator Screen Shot - iPhone 8 - 2023-01-06 at 11 44 13 |

### CODE REVIEW

File: Sources/Private/CoreAnimation/Animations/CALayer+addAnimation.swift [hunk 1]
```diff
@@ -178,11 +178,15 @@ extension CALayer {
...
+        segmentStartTime = min(
+          context.time(for: context.animation.startFrame),
+          segmentStartTime)
       }
 
       if isLastSegment {
-        segmentEndTime = context.time(for: context.animation.endFrame)
+        segmentEndTime = max(
+          context.time(for: context.animation.endFrame),
+          segmentEndTime)
```
Comment (calda) [inline Sources/Private/CoreAnimation/Animations/CALayer+addAnimation.swift:189]: There was also an issue where incorrect logic here could cause us to create invalid `CAAnimation`s, causing the layer to completely disappear.

In this animation, with a start time of 0 and an end time of 50, had keyframes that spanned from -15 to 65. We were incorrectly truncating the segment start / end times here, which was somehow breaking the entire layer:

| Before | After |
| ---- | ----- |
| Simulator Screen Shot - iPhone 8 - 2023-01-06 at 11 46 03 | Simulator Screen Shot - iPhone 8 - 2023-01-06 at 11 44 13 |

File: Sources/Private/CoreAnimation/Layers/ShapeLayer.swift [hunk 2]
```diff
@@ -413,24 +413,54 @@ extension Array where Element == ShapeItemLayer.Item {
...
+      // A `CAShapeLayer` can only draw a single fill and a single stroke
+      let hasAtMostOneFill = fills.count <= 1
+      let hasAtMostOneStroke = strokes.count <= 1
+
+      // A `CAShapeLayer` can only draw a stroke on top of a fill -- if the fill is supposed to be
+      // drawn on top of the stroke, then they have to be rendered as separate layers.
+      let strokeDrawnOnTopOfFill: Bool
+      if
+        let strokeIndex = group.otherItems.firstIndex(where: { $0.item.isStroke }),
+        let fillIndex = group.otherItems.firstIndex(where: { $0.item.isStroke })
```
Comment (erichoracek) [inline Sources/Private/CoreAnimation/Layers/ShapeLayer.swift:436]: Couldn't we use `strokesAndFills` instead of `group.otherItems`? Seems like we may iterate over extra items otherwise

**Review by erichoracek — APPROVED** [review]
@calda LGTM! Just one small typo and a question

File: Sources/Private/CoreAnimation/Layers/ShapeLayer.swift (hunk 2 above)
[the remark this answers is not in the document]
Comment (calda) [reply Sources/Private/CoreAnimation/Layers/ShapeLayer.swift:436]: 😅

[the remark this answers is not in the document]
Comment (calda) [reply Sources/Private/CoreAnimation/Layers/ShapeLayer.swift:436]: thanks!

Comment (calda) [reply Sources/Private/CoreAnimation/Layers/ShapeLayer.swift:436]: I think you're right, thanks!
