### PR TITLE
Fix issue where calling `setValueProvider` would reset animation progress

### LINKED ISSUE #2003: Regression: calling `setValueProvider` on an `AnimationView` should not play the animation
## Which Version of Lottie are you using?

Lottie 4.1.3

## Expected Behavior 
Calling `setValueProvider` on an `AnimationView` should not play the animation

## Actual Behavior
Calling `setValueProvider` on an `AnimationView` plays the animation.  We have the following extension:

```swift
extension AnimationView {
    func changeAnimationColor(to color: UIColor) {
        let fillKeypath = AnimationKeypath(keypath: "**.Fill 1.Color")
        let provider = ColorValueProvider(color.lottieColorValue)
        setValueProvider(provider, keypath: fillKeypath)
    }
}
```

Calling `changeAnimationColor` using this extension makes the animation play. With Lottie 3.4.4 which we were using previously, this did not happen.

## Animation JSON

<details>
<summary>JSON</summary>
{"v":"5.6.5","fr":29.9700012207031,"ip":0,"op":16.0000006516934,"w":75,"h":75,"nm":"Activity","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"activity Outlines","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[36.999,37.223,0],"ix":2},"a":{"a":0,"k":[12,12,0],"ix":1},"s":{"a":0,"k":[300,300,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[-1.164,0],[0,1.163],[1.163,0],[0,-1.165]],"o":[[1.163,0],[0,-1.165],[-1.164,0],[0,1.163]],"v":[[0,2.107],[2.106,0.001],[0,-2.107],[-2.106,0.001]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[0.760999971278,0.752999997606,0.745000023935,1]},{"t":8.00000032584668,"s":[1,0.529411792755,0.35686275363,1]}],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[3.106,18.245],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":2,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[-1.164,0],[0,1.163],[1.163,0],[0,-1.164]],"o":[[1.163,0],[0,-1.164],[-1.164,0],[0,1.163]],"v":[[0,2.106],[2.106,0],[0,-2.106],[-2.106,0]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[0.760999971278,0.752999997606,0.745000023935,1]},{"t":8.00000032584668,"s":[1,0.529411792755,0.35686275363,1]}],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[3.106,11.692],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 2","np":2,"cix":2,"bm":0,"ix":2,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[-1.164,0],[0,1.163],[1.163,0],[0,-1.164]],"o":[[1.163,0],[0,-1.164],[-1.164,0],[0,1.163]],"v":[[0,2.107],[2.106,0.001],[0,-2.107],[-2.106,0.001]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[0.760999971278,0.752999997606,0.745000023935,1]},{"t":8.00000032584668,"s":[1,0.529411792755,0.35686275363,1]}],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[3.106,5.606],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 3","np":2,"cix":2,"bm":0,"ix":3,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":5,"s":[{"i":[[0,-0.246],[-0.351,-0.351],[-0.497,0],[0,0],[-0.351,0.351],[0,0.497],[0.351,0.351],[0.496,0],[0,0],[0.227,-0.095],[0.174,-0.174],[0.094,-0.226]],"o":[[0,0.497],[0.351,0.351],[0,0],[0.496,0],[0.351,-0.351],[0,-0.496],[-0.351,-0.351],[0,0],[-0.247,0],[-0.227,0.093],[-0.173,0.174],[-0.095,0.228]],"v":[[-7.958,0],[-7.41,1.324],[-6.085,1.872],[6.085,1.872],[7.41,1.324],[7.958,0],[7.41,-1.324],[6.085,-1.872],[-6.085,-1.872],[-6.801,-1.729],[-7.41,-1.324],[-7.814,-0.717]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":11,"s":[{"i":[[0,-0.246],[-0.351,-0.351],[-0.497,0],[0,0],[-0.351,0.351],[0,0.497],[0.351,0.351],[0.496,0],[0,0],[0.227,-0.095],[0.174,-0.174],[0.094,-0.226]],"o":[[0,0.497],[0.351,0.351],[0,0],[0.496,0],[0.351,-0.351],[0,-0.496],[-0.351,-0.351],[0,0],[-0.247,0],[-0.227,0.093],[-0.173,0.174],[-0.095,0.228]],"v":[[-7.958,0],[-7.41,1.324],[-6.085,1.872],[-4.903,1.872],[-3.579,1.324],[-3.031,0],[-3.579,-1.324],[-4.903,-1.872],[-6.085,-1.872],[-6.801,-1.729],[-7.41,-1.324],[-7.814,-0.717]],"c":true}]},{"t":16.0000006516934,"s":[{"i":[[0,-0.246],[-0.351,-0.351],[-0.497,0],[0,0],[-0.351,0.351],[0,0.497],[0.351,0.351],[0.496,0],[0,0],[0.227,-0.095],[0.174,-0.174],[0.094,-0.226]],"o":[[0,0.497],[0.351,0.351],[0,0],[0.496,0],[0.351,-0.351],[0,-0.496],[-0.351,-0.351],[0,0],[-0.247,0],[-0.227,0.093],[-0.173,0.174],[-0.095,0.228]],"v":[[-7.958,0],[-7.41,1.324],[-6.085,1.872],[6.085,1.872],[7.41,1.324],[7.958,0],[7.41,-1.324],[6.085,-1.872],[-6.085,-1.872],[-6.801,-1.729],[-7.41,-1.324],[-7.814,-0.717]],"c":true}]}],"ix":2,"x":"var $bm_rt;\nfunction easeandwizz_outBounce(t, b, c, d) {\n    if ((t /= d) < 1 / 2.75) {\n        return $bm_sum($bm_mul(c, $bm_mul($bm_mul(7.5625, t), t)), b);\n    } else if (t < 2 / 2.75) {\n        return $bm_sum($bm_mul(c, $bm_sum($bm_mul($bm_mul(7.5625, t -= 1.5 / 2.75), t), 0.75)), b);\n    } else if (t < 2.5 / 2.75) {\n        return $bm_sum($bm_mul(c, $bm_sum($bm_mul($bm_mul(7.5625, t -= 2.25 / 2.75), t), 0.9375)), b);\n    } else {\n        return $bm_sum($bm_mul(c, $bm_sum($bm_mul($bm_mul(7.5625, t -= 2.625 / 2.75), t), 0.984375)), b);\n    }\n}\nfunction easeandwizz_inBounce(t, b, c, d) {\n    return $bm_sum($bm_sub(c, easeandwizz_outBounce($bm_sub(d, t), 0, c, d)), b);\n}\nfunction easeandwizz_inoutBounce(t, b, c, d) {\n    if (t < $bm_div(d, 2))\n        return $bm_sum($bm_mul(easeandwizz_inBounce($bm_mul(t, 2), 0, c, d), 0.5), b);\n    else\n        return easeandwizz_outBounce(t * 2 - d, 0, c, d) * 0.5 + c * 0.5 + b;\n}\nfunction easeAndWizz() {\n    var t, d, sX, eX;\n    var n = 0;\n    if (numKeys > 0) {\n        n = nearestKey(time).index;\n        if (key(n).time > time) {\n            n--;\n        }\n    }\n    if (n > 1 && n < numKeys - 1) {\n        return null;\n    }\n    try {\n        var key1 = key(n);\n        var key2 = key($bm_sum(n, 1));\n    } catch (e) {\n        return null;\n    }\n    t = $bm_sub(time, key1.time);\n    d = $bm_sub(key2.time, key1.time);\n    sX = key1.time;\n    eX = $bm_sub(key2.time, key1.time);\n    if (time < key1.time || time > key2.time) {\n        return null;\n    } else {\n        return valueAtTime(easeandwizz_inoutBounce(t, sX, eX, d));\n    }\n}\n$bm_rt = easeAndWizz() || value;"},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[0.760999971278,0.752999997606,0.745000023935,1]},{"t":8.00000032584668,"s":[1,0.529411792755,0.35686275363,1]}],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[15.042,18.245],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 4","np":2,"cix":2,"bm":0,"ix":4,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":0,"s":[{"i":[[-0.497,0],[0,0],[-0.352,0.351],[0,0.497],[0.35,0.351],[0.497,0],[0,0],[0.351,-0.351],[0,-0.497],[-0.351,-0.351]],"o":[[0,0],[0.497,0],[0.35,-0.351],[0,-0.497],[-0.352,-0.351],[0,0],[-0.497,0],[-0.351,0.351],[0,0.497],[0.351,0.351]],"v":[[-6.085,1.872],[6.085,1.872],[7.411,1.325],[7.958,0.001],[7.411,-1.324],[6.085,-1.872],[-6.085,-1.872],[-7.408,-1.324],[-7.958,0.001],[-7.408,1.325]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":6,"s":[{"i":[[-0.497,0],[0,0],[-0.352,0.351],[0,0.497],[0.35,0.351],[0.497,0],[0,0],[0.351,-0.351],[0,-0.497],[-0.351,-0.351]],"o":[[0,0],[0.497,0],[0.35,-0.351],[0,-0.497],[-0.352,-0.351],[0,0],[-0.497,0],[-0.351,0.351],[0,0.497],[0.351,0.351]],"v":[[-6.085,1.872],[-4.748,1.872],[-3.423,1.325],[-2.876,0.001],[-3.423,-1.324],[-4.748,-1.872],[-6.085,-1.872],[-7.408,-1.324],[-7.958,0.001],[-7.408,1.325]],"c":true}]},{"t":12.00000048877,"s":[{"i":[[-0.497,0],[0,0],[-0.352,0.351],[0,0.497],[0.35,0.351],[0.497,0],[0,0],[0.351,-0.351],[0,-0.497],[-0.351,-0.351]],"o":[[0,0],[0.497,0],[0.35,-0.351],[0,-0.497],[-0.352,-0.351],[0,0],[-0.497,0],[-0.351,0.351],[0,0.497],[0.351,0.351]],"v":[[-6.085,1.872],[6.085,1.872],[7.411,1.325],[7.958,0.001],[7.411,-1.324],[6.085,-1.872],[-6.085,-1.872],[-7.408,-1.324],[-7.958,0.001],[-7.408,1.325]],"c":true}]}],"ix":2,"x":"var $bm_rt;\nfunction easeandwizz_outBounce(t, b, c, d) {\n    if ((t /= d) < 1 / 2.75) {\n        return $bm_sum($bm_mul(c, $bm_mul($bm_mul(7.5625, t), t)), b);\n    } else if (t < 2 / 2.75) {\n        return $bm_sum($bm_mul(c, $bm_sum($bm_mul($bm_mul(7.5625, t -= 1.5 / 2.75), t), 0.75)), b);\n    } else if (t < 2.5 / 2.75) {\n        return $bm_sum($bm_mul(c, $bm_sum($bm_mul($bm_mul(7.5625, t -= 2.25 / 2.75), t), 0.9375)), b);\n    } else {\n        return $bm_sum($bm_mul(c, $bm_sum($bm_mul($bm_mul(7.5625, t -= 2.625 / 2.75), t), 0.984375)), b);\n    }\n}\nfunction easeandwizz_inBounce(t, b, c, d) {\n    return $bm_sum($bm_sub(c, easeandwizz_outBounce($bm_sub(d, t), 0, c, d)), b);\n}\nfunction easeandwizz_inoutBounce(t, b, c, d) {\n    if (t < $bm_div(d, 2))\n        return $bm_sum($bm_mul(easeandwizz_inBounce($bm_mul(t, 2), 0, c, d), 0.5), b);\n    else\n        return easeandwizz_outBounce(t * 2 - d, 0, c, d) * 0.5 + c * 0.5 + b;\n}\nfunction easeAndWizz() {\n    var t, d, sX, eX;\n    var n = 0;\n    if (numKeys > 0) {\n        n = nearestKey(time).index;\n        if (key(n).time > time) {\n            n--;\n        }\n    }\n    if (n > 1 && n < numKeys - 1) {\n        return null;\n    }\n    try {\n        var key1 = key(n);\n        var key2 = key($bm_sum(n, 1));\n    } catch (e) {\n        return null;\n    }\n    t = $bm_sub(time, key1.time);\n    d = $bm_sub(key2.time, key1.time);\n    sX = key1.time;\n    eX = $bm_sub(key2.time, key1.time);\n    if (time < key1.time || time > key2.time) {\n        return null;\n    } else {\n        return valueAtTime(easeandwizz_inoutBounce(t, sX, eX, d));\n    }\n}\n$bm_rt = easeAndWizz() || value;"},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[0.760999971278,0.752999997606,0.745000023935,1]},{"t":8.00000032584668,"s":[1,0.529411792755,0.35686275363,1]}],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[7.062,11.691],"ix":2},"a":{"a":0,"k":[-7.98,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 5","np":2,"cix":2,"bm":0,"ix":5,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":3,"s":[{"i":[[-0.497,0],[0,0],[-0.352,0.351],[0,0.497],[0.35,0.351],[0.497,0],[0,0],[0.351,-0.351],[0,-0.497],[-0.351,-0.351]],"o":[[0,0],[0.497,0],[0.35,-0.351],[0,-0.497],[-0.352,-0.351],[0,0],[-0.497,0],[-0.351,0.351],[0,0.497],[0.351,0.351]],"v":[[-6.085,1.872],[6.085,1.872],[7.411,1.325],[7.958,0.001],[7.411,-1.324],[6.085,-1.872],[-6.085,-1.872],[-7.408,-1.324],[-7.958,0.001],[-7.408,1.325]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":9,"s":[{"i":[[-0.497,0],[0,0],[-0.352,0.351],[0,0.497],[0.35,0.351],[0.497,0],[0,0],[0.351,-0.351],[0,-0.497],[-0.351,-0.351]],"o":[[0,0],[0.497,0],[0.35,-0.351],[0,-0.497],[-0.352,-0.351],[0,0],[-0.497,0],[-0.351,0.351],[0,0.497],[0.351,0.351]],"v":[[-6.085,1.872],[-4.538,1.872],[-3.213,1.325],[-2.666,0.001],[-3.213,-1.324],[-4.538,-1.872],[-6.085,-1.872],[-7.408,-1.324],[-7.958,0.001],[-7.408,1.325]],"c":true}]},{"t":15.0000006109625,"s":[{"i":[[-0.497,0],[0,0],[-0.352,0.351],[0,0.497],[0.35,0.351],[0.497,0],[0,0],[0.351,-0.351],[0,-0.497],[-0.351,-0.351]],"o":[[0,0],[0.497,0],[0.35,-0.351],[0,-0.497],[-0.352,-0.351],[0,0],[-0.497,0],[-0.351,0.351],[0,0.497],[0.351,0.351]],"v":[[-6.085,1.872],[6.085,1.872],[7.411,1.325],[7.958,0.001],[7.411,-1.324],[6.085,-1.872],[-6.085,-1.872],[-7.408,-1.324],[-7.958,0.001],[-7.408,1.325]],"c":true}]}],"ix":2,"x":"var $bm_rt;\nfunction easeandwizz_outBounce(t, b, c, d) {\n    if ((t /= d) < 1 / 2.75) {\n        return $bm_sum($bm_mul(c, $bm_mul($bm_mul(7.5625, t), t)), b);\n    } else if (t < 2 / 2.75) {\n        return $bm_sum($bm_mul(c, $bm_sum($bm_mul($bm_mul(7.5625, t -= 1.5 / 2.75), t), 0.75)), b);\n    } else if (t < 2.5 / 2.75) {\n        return $bm_sum($bm_mul(c, $bm_sum($bm_mul($bm_mul(7.5625, t -= 2.25 / 2.75), t), 0.9375)), b);\n    } else {\n        return $bm_sum($bm_mul(c, $bm_sum($bm_mul($bm_mul(7.5625, t -= 2.625 / 2.75), t), 0.984375)), b);\n    }\n}\nfunction easeandwizz_inBounce(t, b, c, d) {\n    return $bm_sum($bm_sub(c, easeandwizz_outBounce($bm_sub(d, t), 0, c, d)), b);\n}\nfunction easeandwizz_inoutBounce(t, b, c, d) {\n    if (t < $bm_div(d, 2))\n        return $bm_sum($bm_mul(easeandwizz_inBounce($bm_mul(t, 2), 0, c, d), 0.5), b);\n    else\n        return easeandwizz_outBounce(t * 2 - d, 0, c, d) * 0.5 + c * 0.5 + b;\n}\nfunction easeAndWizz() {\n    var t, d, sX, eX;\n    var n = 0;\n    if (numKeys > 0) {\n        n = nearestKey(time).index;\n        if (key(n).time > time) {\n            n--;\n        }\n    }\n    if (n > 1 && n < numKeys - 1) {\n        return null;\n    }\n    try {\n        var key1 = key(n);\n        var key2 = key($bm_sum(n, 1));\n    } catch (e) {\n        return null;\n    }\n    t = $bm_sub(time, key1.time);\n    d = $bm_sub(key2.time, key1.time);\n    sX = key1.time;\n    eX = $bm_sub(key2.time, key1.time);\n    if (time < key1.time || time > key2.time) {\n        return null;\n    } else {\n        return valueAtTime(easeandwizz_inoutBounce(t, sX, eX, d));\n    }\n}\n$bm_rt = easeAndWizz() || value;"},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[0.760999971278,0.752999997606,0.745000023935,1]},{"t":8.00000032584668,"s":[1,0.529411792755,0.35686275363,1]}],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[7.098,5.607],"ix":2},"a":{"a":0,"k":[-7.944,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 6","np":2,"cix":2,"bm":0,"ix":6,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":299.700012207031,"st":0,"bm":0}],"markers":[]}
</details>

### PR DESCRIPTION
**Pull request by calda**
This PR fixes an issue where calling `setValueProvider` would reset the animation progress, and in some cases trigger a paused animation to start animating again. Fixes #2003 

### `playOnce`, after animation has finished:

| Before | After |
| ---- | ---- |
|  |  |

### `playOnce`, while animation is playing:

| Before | After |
| ---- | ---- |
|  |  |

### `autoreverse`, while animation is playing:

| Before | After |
| ---- | ---- |
|  |  |

### CODE REVIEW

File: Sources/Private/CoreAnimation/CoreAnimationLayer.swift [hunk 1]
```diff
@@ -296,32 +307,20 @@ final class CoreAnimationLayer: BaseAnimationLayer {
...
-    switch playbackState {
-    case .paused(let frame):
-      currentFrame = frame
-
-    case .playing:
-      playAnimation(configuration: newConfiguration ?? currentConfiguration)
+    else { return }
+
+    if isAnimationPlaying == true {
+      animationView?.updateInFlightAnimation()
```
Comment (calda) [inline Sources/Private/CoreAnimation/CoreAnimationLayer.swift:319]: Switched from calling `CoreAnimationLayer.playAnimation` to `LottieAnimationView.updateInflightAnimation`, which already handles seamlessly recreating the animation with the `currentFrame`

**Review by erichoracek — APPROVED** [review]
Good stuff!
